# docker-compose -f /home/appstore/appstore_scraping/sample/docker-compose.yml up

version: '3.9'
services:
  mobileIndex_rank_api:
    env_file:
      - app.env
    container_name: mobileIndex_rank_api
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: python starter.py mobileIndex_rank_api
    volumes:
      - /home/appstore/appstore_scraping:/app
      - /data/appstore/images:/images