# docker-compose -f /home/appstore/appstore_scraping/sample/docker-compose.yml up

version: '3.9'
services:
  google_saved_package_scrap:
    env_file:
      - app.env
    container_name: google_saved_package_scrap
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: python starter.py google_saved_package_scrap
    volumes:
      - /home/appstore/appstore_scraping:/app
      - /data/appstore/images:/images