# docker-compose -f .\docker-compose_all.yml down

version: '3.9'
services:
  appleScrapByCategory:
    container_name: appleScrapByCategory
    image: appstore_scraping:latest
  appleScrapBySavedID:
    container_name: appleScrapBySavedID
    image: appstore_scraping:latest
  googleScrapBySavedID:
    container_name: googleScrapBySavedID
    image: appstore_scraping:latest
  mobileIndexAppSearch:
    container_name: mobileIndexAppSearch
    image: appstore_scraping:latest
  mobileIndexRankApi:
    container_name: mobileIndexRankApi
    image: appstore_scraping:latest
  mobileIndexSecretKey:
    container_name: mobileIndexSecretKey
    image: appstore_scraping:latest