version: '3.9'
services:
  apple_category_scrap:
    container_name: apple_category_scrap
    image: appstore_scraping:latest
    environment:
      - ACTION=apple_category_scrap
    volumes:
      - /data/appstore/images:/resource
      - /home/appstore/appstore_scraping/logs:/logs
  google_saved_package_scrap:
    container_name: google_saved_package_scrap
    image: appstore_scraping:latest
    environment:
      - ACTION=google_saved_package_scrap
    volumes:
      - /data/appstore/images:/resource
      - /home/appstore/appstore_scraping/logs:/logs
  mobileIndex_rank_api:
    container_name: mobileIndex_rank_api
    image: appstore_scraping:latest
    environment:
      - ACTION=mobileIndex_rank_api
    volumes:
      - /data/appstore/images:/resource
      - /home/appstore/appstore_scraping/logs:/logs