# docker-compose -f /home/appstore/appstore_scraping/bin/docker-compose_appleScrapBySavedID.yml up --remove-orphans

version: '3.9'
services:
  mobileIndexAppSearch:
    env_file:
      - ../app.env
    container_name: mobileIndexAppSearch
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: /bin/sh /app/apps/mobileIndex/bin/mobileIndexAppSearch.sh
    volumes:
      - /home/appstore/appstore_scraping:/app
      - /data/appstore/images:/images